DROP USER c##lm CASCADE; 
CREATE USER c##lm IDENTIFIED BY lm DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##lm;
GRANT CREATE VIEW, CREATE SYNONYM TO c##lm;
GRANT UNLIMITED TABLESPACE TO c##lm;
ALTER USER c##lm ACCOUNT UNLOCK;